#!/usr/bin/env node
/**
 * Wraps the raw theme files emitted by the Tokens SOT plugin into a
 * hybrid theming strategy: explicit [data-theme] attribute wins, OS
 * preference is the fallback, and the raw files in src/tokens/raw/
 * stay untouched so attendees can re-export from the plugin without
 * losing the theme wiring.
 *
 *   src/tokens/raw/theme-light.css   (input, owned by Tokens SOT)
 *   src/tokens/raw/theme-dark.css    (input, owned by Tokens SOT)
 *      ↓
 *   src/styles/generated/theme-light.css   (output, gitignored)
 *   src/styles/generated/theme-dark.css    (output, gitignored)
 *
 * Run via:
 *   pnpm tokens:sync          # one-shot: wrap + rebuild story manifest
 *   pnpm theme:wrap:watch     # rebuild whenever the raw files change
 */
import { mkdirSync, readFileSync, watch, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const inDir = resolve(__dirname, '../src/tokens/raw');
const outDir = resolve(__dirname, '../src/styles/generated');

const HEADER = '/* Generated by scripts/wrap-theme.mjs — do not edit by hand. */\n';

/**
 * Replace every top-level `:root { … }` block with the given selector list.
 * The Tokens SOT plugin always emits `:root { … }`, so a literal swap is safe.
 */
function reroot(css, selector) {
  return css.replace(/:root\s*\{/g, `${selector} {`);
}

function wrapLight(raw) {
  return HEADER + reroot(raw, ":root,\n[data-theme='light']");
}

function wrapDark(raw) {
  const reScoped = reroot(raw, "[data-theme='dark']");
  const mediaScoped = reroot(raw, ":root:not([data-theme='light'])");
  return (
    HEADER + '@media (prefers-color-scheme: dark) {\n' + mediaScoped + '\n}\n\n' + reScoped + '\n'
  );
}

function build() {
  mkdirSync(outDir, { recursive: true });

  const light = readFileSync(join(inDir, 'theme-light.css'), 'utf8');
  const dark = readFileSync(join(inDir, 'theme-dark.css'), 'utf8');

  writeFileSync(join(outDir, 'theme-light.css'), wrapLight(light));
  writeFileSync(join(outDir, 'theme-dark.css'), wrapDark(dark));

  // eslint-disable-next-line no-console
  console.log(`[theme:wrap] wrote ${outDir}/theme-{light,dark}.css`);
}

build();

if (process.argv.includes('--watch')) {
  // eslint-disable-next-line no-console
  console.log(`[theme:wrap] watching ${inDir}`);
  let timer;
  watch(inDir, { persistent: true }, (_event, filename) => {
    if (!filename || !/^theme-(light|dark)\.css$/.test(filename)) return;
    clearTimeout(timer);
    timer = setTimeout(build, 50);
  });
}
